ALTER TABLE public.gradebooks ADD CONSTRAINT gradebooks_id_class_id_key UNIQUE (id, class_id);

CREATE TABLE public.gradebook_column_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    class_id bigint NOT NULL,
    gradebook_id bigint NOT NULL,
    name text NOT NULL CHECK (length(btrim(name)) > 0),
    sort_order integer NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
    UNIQUE (id, gradebook_id, class_id),
    FOREIGN KEY (gradebook_id, class_id) REFERENCES public.gradebooks(id, class_id) ON DELETE CASCADE
);
CREATE INDEX gradebook_column_groups_gradebook_order_idx
    ON public.gradebook_column_groups(gradebook_id, sort_order, id);
CREATE INDEX gradebook_column_groups_class_id_idx ON public.gradebook_column_groups(class_id);

ALTER TABLE public.gradebook_column_groups ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.gradebook_column_groups TO authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.gradebook_column_groups_id_seq TO authenticated, service_role;
CREATE POLICY "instructors CRUD" ON public.gradebook_column_groups
    FOR ALL TO authenticated USING (public.authorizeforclassinstructor(class_id))
    WITH CHECK (public.authorizeforclassinstructor(class_id));

ALTER TABLE public.gradebook_columns ADD COLUMN group_id bigint;
-- The composite key prevents attaching a column to another course's group, even through a service client.
ALTER TABLE public.gradebook_columns ADD CONSTRAINT gradebook_columns_group_fkey
    FOREIGN KEY (group_id, gradebook_id, class_id)
    REFERENCES public.gradebook_column_groups(id, gradebook_id, class_id)
    ON DELETE SET NULL (group_id);
CREATE INDEX gradebook_columns_group_id_idx ON public.gradebook_columns(group_id);

CREATE POLICY "everyone in class can view" ON public.gradebook_column_groups
    FOR SELECT TO authenticated USING (
        public.authorizeforclass(class_id) AND (
            public.authorizeforclassgrader(class_id) OR EXISTS (
                SELECT 1 FROM public.gradebook_columns c
                WHERE c.group_id = gradebook_column_groups.id
            )
        )
    );

-- Infer legacy membership once. Numeric gaps do not separate adjacent members of the same family.
-- Unnumbered, non-assignment columns stay separate when their meaning cannot be recovered safely.
DO $$
DECLARE
    col record;
    previous_gradebook bigint;
    previous_family text;
    current_group bigint;
    group_order integer := 0;
BEGIN
    FOR col IN
        SELECT gc.*,
            CASE
                WHEN slug LIKE 'assignment-%' THEN 'assignment-' || split_part(slug, '-', 2)
                WHEN slug ~ '-[0-9]+$' THEN regexp_replace(slug, '-[0-9]+$', '')
                ELSE 'column:' || id::text
            END AS family,
            CASE
                WHEN slug LIKE 'assignment-%-%' THEN initcap(split_part(slug, '-', 2))
                WHEN slug LIKE 'assignment-%' THEN name
                WHEN slug ~ '-[0-9]+$' AND name ~ '[ #]+[0-9]+$'
                    THEN regexp_replace(name, '[ #]+[0-9]+$', '')
                WHEN slug ~ '-[0-9]+$' THEN initcap(replace(regexp_replace(slug, '-[0-9]+$', ''), '-', ' '))
                ELSE name
            END AS group_name
        FROM public.gradebook_columns gc
        ORDER BY gradebook_id, COALESCE(sort_order, 0), id
    LOOP
        IF previous_gradebook IS DISTINCT FROM col.gradebook_id THEN
            group_order := 0;
            previous_family := NULL;
        END IF;
        IF previous_family IS DISTINCT FROM col.family THEN
            INSERT INTO public.gradebook_column_groups(class_id, gradebook_id, name, sort_order)
            VALUES (col.class_id, col.gradebook_id, COALESCE(NULLIF(btrim(col.group_name), ''), 'Other'), group_order)
            RETURNING id INTO current_group;
            group_order := group_order + 1;
        END IF;
        UPDATE public.gradebook_columns SET group_id = current_group WHERE id = col.id;
        previous_gradebook := col.gradebook_id;
        previous_family := col.family;
    END LOOP;
END;
$$;

-- Group labels may reveal instructor-only column names, so broadcasts stay on the staff channel.
CREATE FUNCTION public.broadcast_gradebook_column_groups_change()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE
    changed public.gradebook_column_groups;
BEGIN
    IF TG_OP = 'DELETE' THEN changed := OLD; ELSE changed := NEW; END IF;
    PERFORM public.safe_broadcast(jsonb_build_object(
        'type', 'table_change', 'operation', TG_OP, 'table', TG_TABLE_NAME,
        'row_id', changed.id, 'data', to_jsonb(changed), 'class_id', changed.class_id,
        'target_audience', 'staff', 'timestamp', now()
    ), 'broadcast', 'class:' || changed.class_id || ':staff', true);
    RETURN changed;
END;
$$;
CREATE TRIGGER broadcast_gradebook_column_groups
    AFTER INSERT OR UPDATE OR DELETE ON public.gradebook_column_groups
    FOR EACH ROW EXECUTE FUNCTION public.broadcast_gradebook_column_groups_change();

CREATE FUNCTION public.gradebook_column_groups_reorder(p_gradebook_id bigint, p_group_ids bigint[])
RETURNS void LANGUAGE plpgsql SECURITY INVOKER SET search_path = public, pg_temp AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM public.gradebooks
        WHERE id = p_gradebook_id AND public.authorizeforclassinstructor(class_id)
    ) THEN
        RAISE EXCEPTION 'Instructor access required';
    END IF;
    PERFORM pg_advisory_xact_lock(p_gradebook_id);
    IF cardinality(p_group_ids) IS NULL
        OR cardinality(p_group_ids) <> (SELECT count(*) FROM public.gradebook_column_groups WHERE gradebook_id = p_gradebook_id)
        OR cardinality(p_group_ids) <> (SELECT count(DISTINCT id) FROM unnest(p_group_ids) id)
        OR EXISTS (
            SELECT 1 FROM unnest(p_group_ids) supplied(id)
            WHERE NOT EXISTS (SELECT 1 FROM public.gradebook_column_groups g WHERE g.id = supplied.id AND g.gradebook_id = p_gradebook_id)
        ) THEN
        RAISE EXCEPTION 'Provide every group in this gradebook exactly once';
    END IF;
    UPDATE public.gradebook_column_groups g SET sort_order = ordered.position - 1
    FROM unnest(p_group_ids) WITH ORDINALITY ordered(id, position)
    WHERE g.id = ordered.id AND g.gradebook_id = p_gradebook_id;
END;
$$;
REVOKE ALL ON FUNCTION public.gradebook_column_groups_reorder(bigint, bigint[]) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.gradebook_column_groups_reorder(bigint, bigint[]) TO authenticated;
